Renamed `arch_as_root` script to `arch_0`
Now this first installation script doesn't have to be run as root.
Instead, the idea is you'll download this script (e.g.: with `curl`)
and run it straight off. It will then detect whether you're a root user,
and if so create a normal user account as required, then it will run the
rest of the script as that unpriviledged user to improve security, or,
if the current user was already unpriviledged, just exec the rest of the
script.

Then the script will attempt to clone the dotfiles, run `dotf checkout`
automatically, and then run the actual 'install' script
`.config/bin/install/arch`.

diff --git a/.config/bin/install/definitions b/.config/bin/install/definitions
--- a/.config/bin/install/definitions
+++ b/.config/bin/install/definitions
@@ -20,15 +20,15 @@ case $1 in
         ;;
 esac
 
-function handle_exit {
-    if [ "$?" -eq 0 ]; then
-        echo -e "Clean exit"
-    elif [ "$?" -eq 196238 ]; then
-        echo -e "User aborted script"
-    else
-        echo -e "${BOLD}====>${RESET_FMT} \`${last_command}\` ${RED}${BOLD}failed with exit code $?, aborting install...${RESET_FMT}"
-    fi
-}
+# function handle_exit {
+#     if [ "$?" -eq 0 ]; then
+#         echo -e "Clean exit"
+#     elif [ "$?" -eq 196238 ]; then
+#         echo -e "User aborted script"
+#     else
+#         echo -e "${BOLD}====>${RESET_FMT} \`${last_command}\` ${RED}${BOLD}failed with exit code $?, aborting install...${RESET_FMT}"
+#     fi
+# }
 
 function header {
 	echo -e "${BOLD}====> ${BLUE}$1${RESET_FMT}"
