Huge update to waybar colors, theming support, fish prompt etc...
Also added vim plugin to VS Code (though actual Vim still seems faster
to me), and fixed up .tmux.conf for latest version of tmux.

Also switched to fzf as an application launcher - looks quite snazzy.
Can use Super+D to launch apps in background, and Super+X to bring a up
a large terminal window.

Ctrl+R now opens an fzf menu of binaries in the path - which can be
useful to choose a command but then edit arguments later.

diff --git a/.config/bin/wpaper b/.config/bin/wpaper
--- a/.config/bin/wpaper
+++ b/.config/bin/wpaper
@@ -2,7 +2,13 @@
 
 echo "Select a new wallpaper:"
 mkdir -p ~/Pictures
-wallpaper=$(ls ~/Pictures | grep -v "wallpaper-current" | fzf --reverse --height=10 --min-height=5)
+wallpaper=$(cd ~/Pictures && find . -maxdepth 1 -type f | sed 's/^\.\///g'| grep -v "wallpaper-current" | fzf --reverse --height=10 --min-height=5)
+
+if [ "$wallpaper" = '' ]; then
+    echo "No wallpaper selected, aborting..."
+    exit 1
+fi
+
 wallpaper="$HOME/Pictures/$wallpaper"
 ln -sf $wallpaper ~/Pictures/wallpaper-current.jpg && echo "'wallpaper-current.jpg' points to '$wallpaper'"
 
